SELECT P.NAZIV, I.DATPOLAGANJA, I.OCENA
FROM DA.ISPIT I JOIN DA.PREDMET P ON I.IDPREDMETA = P.ID
WHERE STATUS = 'o' AND OCENA > 5;

-- -------------------------------------------------------

WITH PRVIPOLOZEN AS (
  SELECT I.INDEKS, MIN(I.DATPOLAGANJA) AS DATPRVOG
  FROM DA.ISPIT I 
  WHERE I.OCENA > 5 AND I.STATUS = 'o'
  GROUP BY I.INDEKS, I.DATPOLAGANJA
  HAVING I.DATPOLAGANJA IS NOT NULL
)
SELECT INDEKS, IME, PREZIME 
FROM DA.DOSIJE D 
WHERE EXISTS (
  SELECT * 
  FROM PRVIPOLOZEN PP
  WHERE PP.INDEKS = D.INDEKS AND EXISTS (
    SELECT * 
    FROM DA.STUDIJSKIPROGRAM SP 
    WHERE D.IDPROGRAMA = SP.ID AND SP.NAZIV = 'Informatika'
  )
);

-- ------------------------------------------------------------

WITH PRVIPOLOZEN AS (
  -- PRVI POLOZEN ISPIT I DA JE NA INFORMATICI
  SELECT I.INDEKS, MIN(I.DATPOLAGANJA) DATPRVOG
  FROM DA.ISPIT I JOIN DA.DOSIJE D ON D.INDEKS = I.INDEKS 
       JOIN DA.STUDIJSKIPROGRAM SP ON SP.ID = D.IDPROGRAMA 
  WHERE I.OCENA > 5 AND I.STATUS = 'o'
  GROUP BY I.INDEKS, I.DATPOLAGANJA
  HAVING I.DATPOLAGANJA IS NOT NULL
)
SELECT  I.INDEKS, 
        (SELECT IME FROM DA.DOSIJE D WHERE D.INDEKS = I.INDEKS), 
        (SELECT PREZIME FROM DA.DOSIJE D WHERE D.INDEKS = I.INDEKS), 
        I.DATPOLAGANJA, 
        (SELECT NAZIV FROM DA.PREDMET P WHERE P.ID = I.IDPREDMETA) 
FROM DA.ISPIT I 
WHERE EXISTS (
  SELECT * 
  FROM PRVIPOLOZEN PP 
  WHERE PP.INDEKS = I.INDEKS AND PP.DATPRVOG = I.DATPOLAGANJA
);

-- --------------------------------------------------------------

-- STUDIJSKI PROGRAM 
SELECT ID, NAZIV
FROM DA.STUDIJSKIPROGRAM SP 
ORDER BY SP.NAZIV;


-- PADALI NEKI ISPIT 

SELECT D.IME, D.PREZIME, D.INDEKS, D.IDPROGRAMA
FROM DA.DOSIJE D 
WHERE D.IDPROGRAMA = 103 AND  EXISTS (
  SELECT * 
  FROM DA.ISPIT I 
  WHERE I.INDEKS = D.INDEKS AND I.OCENA = 5 AND I.STATUS = 'o'
)
ORDER BY D.INDEKS;

-- ------------------------------------------------------------

-- ZA SVAKI SMER --> STUD SA NAJVISE POLOZENIH ESPB

WITH NAJVISEPOLOZENIHESPB AS (
  SELECT I.INDEKS, SUM(ESPB) SUMAESPB, D.IDPROGRAMA
  FROM  DA.DOSIJE D JOIN DA.ISPIT I ON I.INDEKS = D.INDEKS
        JOIN DA.PREDMET P ON P.ID = I.IDPREDMETA
  WHERE I.OCENA > 5 AND I.STATUS = 'o'
  GROUP BY I.INDEKS, D.IDPROGRAMA
)
SELECT NPE.INDEKS, NPE.SUMAESPB
FROM NAJVISEPOLOZENIHESPB NPE JOIN DA.DOSIJE D ON NPE.INDEKS = D.INDEKS
WHERE NPE.SUMAESPB IN (
  SELECT MAX(NPE1.SUMAESPB)
  FROM NAJVISEPOLOZENIHESPB NPE1
  WHERE NPE.IDPROGRAMA = NPE1.IDPROGRAMA
)
ORDER BY NPE.IDPROGRAMA;

-- POSLEDNJI POLOZEN ISPIT

WITH POSLEDNJIPOLOZEN AS (
  SELECT INDEKS, MAX(DATPOLAGANJA) DATPOSLEDNJEG
  FROM DA.ISPIT 
  WHERE OCENA > 5 AND STATUS = 'o'
  GROUP BY INDEKS, DATPOLAGANJA
  HAVING DATPOLAGANJA IS NOT NULL
)
SELECT INDEKS 
FROM DA.ISPIT I 
WHERE I.INDEKS = :hIndeks AND EXISTS (
  SELECT * 
  FROM POSLEDNJIPOLOZEN PP
  WHERE PP.INDEKS = I.INDEKS AND PP.DATPOSLEDNJEG = I.DATPOLAGANJA
)