DROP TABLE IF EXISTS DA.OBRADJENIPREDMETI;

CREATE TABLE DA.OBRADJENIPREDMETI(
  IDPREDMETA INT NOT NULL PRIMARY KEY,
  FOREIGN KEY(IDPREDMETA) REFERENCES DA.PREDMET
);

-- ------------------------------------------

DROP TABLE IF EXISTS DA.STATISTIKAPOLAGANJA;

CREATE TABLE DA.STATISTIKAPOLAGANJA(
  SKGODINA SMALLINT NOT NULL,
  OZNAKAROKA VARCHAR(20) NOT NULL,
  IDPREDMETA INTEGER NOT NULL,
  USPESNOST DOUBLE,
  PRIMARY KEY(SKGODINA, OZNAKAROKA, IDPREDMETA),
  FOREIGN KEY (SKGODINA, OZNAKAROKA) REFERENCES DA.ISPITNIROK,
  FOREIGN KEY (IDPREDMETA) REFERENCES DA.PREDMET
);

