SELECT INDEKS, P.NAZIV
FROM DA.ISPIT I JOIN DA.PREDMET ON I.IDPREDMETA = P.ID
WHERE OCENA > 5 AND STATUS = 'o'
ORDER BY INDEKS;

-- OVAJ UPIT KORISTIMO, JER ZELIMO DA AZURIRAMO
SELECT INDEKS, (SELECT P.NAZIV FROM DA.PREDMET P WHERE P.ID = I.IDPREDMETA)
FROM DA.ISPIT I
WHERE OCENA > 5 AND STATUS = 'o'
ORDER BY  INDEKS

-- ----------------------------------------------------------

SELECT NAZIV, ESPB
FROM DA.PREDMET P
WHERE P.ID IN (
        SELECT IDPREDMETA
        FROM DA.PREDMETPROGRAMA PP
        WHERE PP.IDPROGRAMA = 103 AND VRSTA = 'obavezan'
    );

-- ------------------------------------------


