SELECT  P.NAZIV, I.DATPOLAGANJA, I.OCENA 
FROM    DA.ISPIT I JOIN DA.PREDMET P ON I.IDPREDMETA = P.ID 
WHERE   I.INDEKS = 20192033 AND I.STATUS = 'o' AND I.OCENA > 5;

-- ----------------------------------------------------------

SELECT I.INDEKS, D.IME, D.PREZIME, I.DATPOLAGANJA, P.NAZIV 
FROM  DA.ISPIT I JOIN DA.PREDMET P ON I.IDPREDMETA = P.ID 
      JOIN DA.DOSIJE D ON D.INDEKS = I.INDEkS 
      JOIN DA.STUDIJSKIPROGRAM SP ON SP.ID = D.IDPROGRAMA
WHERE I.OCENA > 5 AND I.STATUS = 'o' AND 
      I.DATPOLAGANJA = (
        SELECT MIN(I1.DATPOLAGANJA) 
        FROM DA.ISPIT I1
        WHERE I.INDEKS = I1.INDEKS
        HAVING MIN(I1.DATPOLAGANJA) IS NOT NULL
        )

-- 2363 

-- ----------------------------------------------------------

WITH POM AS (
  SELECT D.INDEKS, MIN(DATPOLAGANJA) AS DATPRVOG
  FROM DA.ISPIT I JOIN DA.DOSIJE D ON D.INDEKS = I.INDEKS
      JOIN DA.STUDIJSKIPROGRAM SP ON SP.ID = D.IDPROGRAMA 
  WHERE OCENA > 5 AND STATUS = 'o' AND SP.NAZIV = 'Informatika'
  GROUP BY D.INDEKS 
  HAVING MIN(DATPOLAGANJA) IS NOT NULL
)
SELECT  I.INDEKS, (SELECT IME FROM DA.DOSIJE D WHERE I.INDEKS = D.INDEKS), 
        (SELECT PREZIME FROM DA.DOSIJE D WHERE D.INDEKS = I.INDEKS),
        (SELECT P.NAZIV FROM DA.PREDMET P WHERE P.ID = I.IDPREDMETA),
        I.DATPOLAGANJA
FROM    DA.ISPIT I 
WHERE  EXISTS (
  SELECT * 
  FROM POM AS P1 
  WHERE P1.INDEKS = I.INDEKS AND P1.DATPRVOG = I.DATPOLAGANJA 
);

-------------------------------------------------------------------------------

1. IME, PREZIME, INDEKS ---> PALI SU NEKI ISPIT 

SELECT IME, PREZIME, INDEKS, IDPROGRAMA
FROM DA.DOSIJE D
WHERE EXISTS (
  SELECT * 
  FROM DA.ISPIT I 
  WHERE I.INDEKS = D.INDEKS AND I.OCENA = 5 AND I.STATUS = 'o'
);

SELECT SP.ID, SP.NAZIV 
FROM DA.STUDIJSKIPROGRAM SP 
ORDER BY SP.NAZIV

-- -------------------------------------------------------------------------------
-- 6. 

-- NAJVISE POLOZENIH ESPB 

WITH POM AS (
  SELECT I.INDEKS, SUM(P.ESPB) SUMA, D.IDPROGRAMA
  FROM DA.ISPIT I JOIN DA.DOSIJE D ON I.INDEKS = D.INDEKS
      JOIN DA.PREDMET P ON P.ID = I.IDPREDMETA
  WHERE I.OCENA > 5 AND I.STATUS = 'o'
  GROUP BY I.INDEKS, D.IDPROGRAMA 
)
SELECT D.INDEKS, P1.SUMA, P1.IDPROGRAMA
FROM POM P1 JOIN DA.DOSIJE D ON P1.INDEKS = D.INDEKS
WHERE P1.SUMA IN (
  SELECT MAX(P2.SUAM)
  FROM POM P2
  WHERE P2.IDPROGRAMA = P1.IDPROGRAMA
)
ORDER BY P1.IDPROGRAMA 

-- POSLEDNJI POLOZENI ISPIT 

WITH POM AS (
  SELECT I.INDEKS, MAX(DATPOLAGANJA) DATPOSLEDNJEG
  FROM DA.ISPIT I JOIN DA.DOSIJE D ON D.INDEKS = I.INDEKS
  WHERE I.OCENA > 5 AND I.STATUS = 'o'
  GROUP BY I.INDEKS 
  HAVING MAX(DATPOLAGANJA) IS NOT NULL
)
SELECT INDEKS 
FROM DA.ISPIT I 
WHERE I.INDEKS = :hIndeks AND 
  EXISTS (
    SELECT *
    FROM POM P1 
    WHERE I.INDEKS = P1.INDEKS AND P1.DATPOSLEDNJEG = I.DATPOLAGANJA
  )
  