SELECT  D.INDEKS, IME, PREZIME, OCENA
FROM    DA.DOSIJE D JOIN DA.ISPIT I ON D.INDEKS = I.INDEKS
        JOIN DA.PREDMET P ON P.ID = I.IDPREDMETA 
WHERE   P.NAZIV = 'Programiranje 1' AND SKGODINA = 2018 AND OZNAKAROKA = 'jan1' 
        AND OCENA IS NOT NULL AND STATUS = 'o';

-- ------------------------------------------------------------------------------

-- ISPITNI ROKOVI

SELECT    IR.SKGODINA, IR.OZNAKAROKA, NAZIV, OCENA, COUNT(*) BROJ 
FROM      DA.ISPITNIROK IR JOIN DA.ISPIT I ON IR.SKGODINA = I.SKGODINA AND IR.OZNAKAROKA = I.OZNAKAROKA
WHERE     OCENA > 5 AND STATUS = 'o'
GROUP BY  IR.SKGODINA, IR.OZNAKAROKA, NAZIV, OCENA
ORDER BY  IR.SKGODINA, IR.OZNAKAROKA, OCENA;

-------------------------------------------------------

-- POLAGANJE 
-- KORISTI SE ZA BRISANJE!
-- KAKO CEMO DA IZDVAJAMO ODGOVARAJUCE REDOVE?

SELECT  INDEKS, IDPREDMETA, SKGODINA, OZNAKAROKA, DATPOLAGANJA
FROM    DA.ISPIT 
WHERE   OCENA > 5 AND STATUS = 'o' AND SKGODINA = ? AND OZNAKAROKA = ?;
