INDEKS, IME, PREZIME, NAZIV_SP 
STUDENATA KOJI SU POLOZILI TACNO N PREDMETA 


WITH POMOCNA AS (
  SELECT INDEKS
  FROM DA.ISPIT 
  WHERE OCENA > 5 AND STATUS = 'o'
  GROUP BY INDEKS 
  HAVING COUNT(*) = ?
)
SELECT INDEKS, IME, PREZIME, SP.NAZIV 
FROM DA.DOSIJE D JOIN DA.STUDIJSKIPROGRAM SP ON SP.ID = D.IDPROGRAMA 
WHERE EXISTS (
  SELECT * 
  FROM POMOCNA P 
  WHERE P.INDEKS = D.INDEKS
)

SELECT NAZIV 
FROM DA.ISPIT I JOIN DA.PREDMET P ON P.ID = I.IDPREDMETA 
WHERE OCENA > 5 AND STATUS = 'o' AND I.INDEKS = ?;

-- ----------------------------------------------------------

IME, PREZIME, DATDIPLOMIRANJA 
STUDENTINJE, IDPROGRAMA 

SELECT IME, PREZIME, DATDIPLOMIRANJA 
FROM DA.DOSIJE 
WHERE POL = 'z' AND IDPROGRAMA = 202

-- ---------------------------------------------------------

SELECT SKGODINA, OZNAKAROKA, NAZIV, DATPOCETKA, DATKRAJA 
FROM DA.ISPITNIROK 
ORDER BY NAZIV

-- ------------------------------------------

CREATE TABLE DA.UNETIPREDMETI (
  IDPREDMETA INT NOT NULL PRIMARY KEY,
  BROJ_POLOZENIH INT, 
  CONSTRAINT fk_unetipredmeti FOREIGN KEY(IDPREDMETA) REFERENCES ON DA.PREDMET(ID)
)

SELECT I.IDPREDMETA, COUNT(*)
FROM DA.ISPIT I 
WHERE I.STATUS = 'o' AND I.OCENA > 5 AND I.IDPREDMETA NOT IN (
  SELECT UP.IDPREDMETA 
  FROM DA.UNETIPREDMETI UP 
)
GROUP BY I.IDPREDMETA;

-- ----------------------------------------------------

SELECT * 
FROM DA.ISPIT 
WHERE STATUS = 'o' AND OCENA = 5 AND SKGODINA = 2016

-- -----------------------------------------------------

SELECT INDEKS, (SELECT NAZIV FROM DA.PREDMET P WHERE P.ID = I.IDPREDMETA)
FROM DA.ISPIT I  
WHERE OCENA = 5 AND STATUS = 'o'
ORDER BY INDEKS