-- ISPITNI ROK ZA KOJI POSTOJI MAKAR JEDNO POLAGANJE 

WITH POMOCNA AS (
  SELECT I.SKGODINA, I.OZNAKAROKA
  FROM DA.ISPIT I JOIN DA.ISPITNIROK IR ON IR.SKGODINA = I.SKGODINA AND IR.OZNAKAROKA = I.OZNAKAROKA
  WHERE OCENA > 5 AND STATUS = 'o'
)
SELECT NAZIV, SKGODINA
FROM DA.ISPITNIROK IR 
WHERE EXISTS (
  SELECT *
  FROM POMOCNA POM
  WHERE POM.SKGODINA = IR.SKGODINA AND POM.OZNAKAROKA = IR.OZNAKAROKA
);


SELECT IR.NAZIV, IR.SKGODINA
FROM DA.ISPITNIROK IR 
WHERE EXISTS (
  SELECT *
  FROM DA.ISPIT I
  WHERE I.SKGODINA = IR.SKGODINA AND I.OZNAKAROKA = IR.OZNAKAROKA AND
        I.OCENA > 5 AND I.STATUS = 'o'
);

-- ----------------------------------------------------------------------------

-- ZA SVAKI PROGRAM KOJI SE NE NALAZI U DA.OBRADJENI OPREDMETI 
-- IZLISTAVA NAZIV I ESPB 


SELECT NAZIV, ESPB
FROM DA.PREDMET P 
WHERE P.ID NOT IN (
  SELECT OP.IDPREDMETA 
  FROM DA.OBRADJENIPREDMETI OP
) 